apps/productos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from . import views

app_name = "productos"

urlpatterns = [
    # CATEGORIAS
    path("crear/categorias/", views.crear_categorias, name="crear_categorias"),
    path("crear/editar_categorias/<int:pk>/", views.UpdateCategorias.as_view(), name="editar_categoria"),
    path("productos/eliminar_categoria/<int:pk>/", views.eliminar_categoria, name="eliminar_categoria"),
    # SUB CATEGORIAS
    path("crear/sub_categorias/", views.crear_sub_categorias, name="crear_subcategorias"),
    path("productos/eliminar_subcategoria/<int:pk>/", views.eliminar_subcategoria, name="eliminar_subcategoria"),
    path("crear/editar_subcategorias/<int:pk>/", views.UpdateSubCategorias.as_view(), name="editar_subcategoria"),
    # AMBAS
    path("sub_categorias/", views.sub_categorias, name="mostrar_categorias_subcategorias"),
    # Esto asegura que se carguen correctamente los archivos de static
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("crear/", views.CrearProductos.as_view(), name="crear_productos"),
    path("productos/", views.ListProductos.as_view(), name="productos"),
    path("productos/eliminar_producto/<int:pk>/", views.eliminar_producto, name="eliminar_producto"),
    path("productos/editar_producto/<int:pk>/", views.UpdateProductos.as_view(), name="editar_producto"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("cuentas/", include(("cuentas.urls", "cuentas"))),
    path("productos/", include(("productos.urls", "productos"))),
    path("ventas/", include(("ventas.urls", "ventas"))),
    path("", include(("core.urls", "core"))),
    path("Tienda/", include(("Tienda.urls", "Tienda"))),
]

apps/productos/models.py
from django.core.validators import MinValueValidator
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit


class Categorias(models.Model):
    categoria_name = models.CharField(max_length=50, verbose_name="Nombre", default="", null=True, blank=False)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        app_label = "productos"

    def __str__(self):
        return f"{self.categoria_name}"


class SubCategorias(models.Model):
    categoria = models.ForeignKey(
        Categorias, max_length=50, verbose_name="Nombre", on_delete=models.CASCADE, null=True, blank=False
    )
    sub_categoria = models.CharField(max_length=50, verbose_name="Nombre", default="", null=False, blank=False)

    class Meta:
        verbose_name = "Subcategoria"
        verbose_name_plural = "Subcategorias"
        app_label = "productos"

    def __str__(self):
        return f"{self.sub_categoria}"


class Productos(models.Model):
    nombre_categoria = models.ForeignKey(Categorias, max_length=50, on_delete=models.SET_NULL, null=True, blank=True)
    nombre_subcategoria = models.ForeignKey(
        SubCategorias, max_length=50, on_delete=models.SET_NULL, null=True, blank=True
    )

    nombre = models.CharField(max_length=50, verbose_name="Nombre", default="", null=False, blank=False)
    precio = models.DecimalField(
        verbose_name="Precio", max_digits=10, blank=False, decimal_places=2, validators=[MinValueValidator(0)]
    )
    stock = models.PositiveSmallIntegerField(default=0, verbose_name="Stock", null=True, blank=True)
    image = models.ImageField(upload_to="productos", null=False, blank=False, default=None)
    image_thumbnail = ImageSpecField(
        source="image", processors=[ResizeToFit(300, 300)], format="PNG", options={"quality": 90}
    )
    digital = models.BooleanField(default=False, null=False, blank=False)
    descripcion = models.TextField(max_length=250, null=True, blank=True)

    @property
    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        app_label = "productos"

    def __str__(self):
        return f"{self.nombre}"

apps/productos/forms.py
# crispy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from productos.models import Categorias, SubCategorias

# apps
from .models import Productos


class ProductosForm(forms.ModelForm):
    image = forms.ImageField(
        label="Imagen",
        required=True,
    )
    digital = forms.ChoiceField(
        choices=((1, "Sí"), (0, "No")),
        widget=forms.RadioSelect(),
        initial=0,
        required=True,
    )
    stock = forms.IntegerField(
        label="Stock",
        required=True,
    )

    class Meta:
        model = Productos
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


# Estos dos forms podría haberlos hecho sin usar forms.py pero quería reutilizar el html
class CategoriasForm(forms.ModelForm):
    class Meta:
        model = Categorias
        # Esto va así para que si cambio el nombre en models no se rompa esto y tenga que cambiarlo
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class SubCategoriasForm(forms.ModelForm):
    class Meta:
        model = SubCategorias
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"

apps/productos/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView
from productos.models import Categorias, Productos, SubCategorias

from apps import productos

from .forms import CategoriasForm, ProductosForm, SubCategoriasForm


class CrearProductos(CreateView):
    model = Productos
    template_name = "productos/crear.html"
    form_class = ProductosForm
    success_url = reverse_lazy("productos:productos")


class UpdateProductos(UpdateView):
    model = Productos
    template_name = "productos/crear.html"
    form_class = ProductosForm
    success_url = reverse_lazy("productos:productos")

    def get_pk(self, pk):
        producto = Productos.objects.get(id=pk)
        return producto


class ListProductos(ListView):
    model = Productos
    template_name = "productos/productos.html"
    fields = "__all__"

    def get_queryset(self):
        query = self.request.GET.get("buscar")
        if query:
            productos = Productos.objects.filter(nombre__icontains=query)
            if not productos:
                messages.warning(self.request, "No se encontraron resultados")
            return productos
        else:
            productos = Productos.objects.all()
        return productos


def eliminar_producto(request, pk):
    producto = Productos.objects.get(id=pk)
    producto.delete()
    messages.success(request, "Se ha eliminado el producto exitosamente.")
    return redirect("productos:productos")


# Ordenar por nombre
# * Ver después
# def ordenar_productos(self, request):
#     sort_by = self.request.POST.get("sort_criteria")

#     if sort_by == "nombre":
#         orden = self.get_queryset().order_by("nombre")
#         print("Se ha elegido ordenar por nombre")
#     elif sort_by == "precio":
#         orden = self.get_queryset().order_by("nombre")
#         print("Se ha elegido ordenar por precio")
#     elif sort_by == "categoria":
#         orden = self.get_queryset().order_by("nombre")
#         print("Se ha elegido ordenar por categoría")
#     else:
#         orden = self.get_queryset().order_by("nombre")
#         print("Se ha elegido ordenar por subcategoría")

#     return (request, {"data": orden}, "productos/productos.html")


# * Muestra todas las subcategorías y categorías en un solo template
def sub_categorias(request):
    contexto = {}
    categorias = Categorias.objects.all()
    sub_categorias = SubCategorias.objects.all()
    contexto["categorias"] = categorias
    contexto["sub_categorias"] = sub_categorias

    return render(request, "productos/sub_categorias.html", contexto)


def crear_categorias(request):
    form = CategoriasForm()

    if request.method == "POST":
        form = CategoriasForm(request.POST)
        if form.is_valid():
            form.save()
            # Ver mensaje
            categoria = form.cleaned_data.get("categoria_name")
            messages.success(request, f"Categoria creada exitosamente: {categoria}")
            return redirect("index")

    contexto = {"form": form}
    return render(request, "productos/crear.html", contexto)


class UpdateCategorias(UpdateView):
    model = Categorias
    template_name = "productos/crear.html"
    form_class = CategoriasForm
    success_url = reverse_lazy("index")

    def get_pk(self, pk):
        categoria = Categorias.objects.get(id=pk)
        return categoria


def eliminar_categoria(request, pk):
    categoria = Categorias.objects.get(id=pk)
    categoria.delete()
    messages.success(request, "Se ha eliminado la categoria exitosamente.")
    return redirect("index")


# SUB CATEGORIAS
class UpdateSubCategorias(UpdateView):
    model = SubCategorias
    template_name = "productos/crear.html"
    form_class = SubCategoriasForm
    success_url = reverse_lazy("index")

    def get_pk(self, pk):
        subcategoria = SubCategorias.objects.get(id=pk)
        return subcategoria


def crear_sub_categorias(request):
    form = SubCategoriasForm()

    if request.method == "POST":
        form = SubCategoriasForm(request.POST)
        if form.is_valid():
            form.save()
            # Ver mensaje
            subcategoria = form.cleaned_data.get("sub_categoria")
            messages.success(request, f"Subcategoria creada exitosamente:{subcategoria}")
            return redirect("index")

    contexto = {"form": form}
    return render(request, "productos/crear.html", contexto)


def eliminar_subcategoria(request, pk):
    sub_categoria = SubCategorias.objects.get(id=pk)
    sub_categoria.delete()
    messages.success(request, "Se ha eliminado la subcategoria exitosamente.")
    return redirect("index")

apps/productos/templates/productos/crear.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block contenido %}
<html lang="es-ar">


    <body>
        <h1 id="editar_categoria-heading" style="display: none;">Editar Categoria: {{ categorias }}</h1>
        <h1 id="categoria-heading" style="display: none;">Nueva categoria </h1>

        <h1 id="update-subcategoria-heading" style="display: none;">Editar Subcategoria: {{ sub_categoria }} </h1>
        <h1 id="subcategoria-heading" style="display: none;">Nueva Subcategoria </h1>
        
        <h1 id="crear_producto-heading" style="display: none;">Nuevo producto </h1>
        <h1 id="editar_producto-heading" style="display: none;">Editar producto: {{ productos.nombre }} </h1>

<script type="text/javascript">
    
    const currentUrl = window.location.href;
    //Cambia el título según url
    //categorias y subcategorias
    if (currentUrl.includes("productos/crear/categorias")) {
        document.getElementById("categoria-heading").style.display = "block";

    } else if (currentUrl.includes("productos/crear/sub_categorias")) {
        document.getElementById("subcategoria-heading").style.display = "block";
        
    } else if (currentUrl.includes("/productos/crear/editar_categorias/")) {
        document.getElementById("editar_categoria-heading").style.display = "block";
        //productos
    } else if (currentUrl.includes( "/productos/crear/editar_subcategorias/")) {
        document.getElementById("update-subcategoria-heading").style.display = "block";
        
        

    } else if (currentUrl.includes("/productos/productos/editar_producto/")) {
        document.getElementById("editar_producto-heading").style.display = "block";
        
    } else {
       
        document.getElementById("crear_producto-heading").style.display = "block";
    }

    
    

</script>

        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Guardar">
                
                {% if form.instance.imagen_thumbnail %}
                    <img src="{{ form.instance.imagen_thumbnail.url }}" alt="Imagen miniatura">
                {% endif %}
                <script>
                    
                </script>
            </form>
        </div>
    </body>
</html>

{% endblock contenido %}

apps/productos/templates/productos/productos.html
{% extends "core/base.html" %}

{% block contenido %}
<!DOCTYPE html>
<html lang="es-ar">

<script src="https://unpkg.com/htmx.org@latest/dist/htmx.js"></script>

    <body>
<style>
        .thumbnail {
            width: 100px; 
            height: 100px; 
            object-fit: cover; 
            border: 1px solid #ccc; 
            border-radius: 4px; 
                }
        .messages {

            background-color: #d4edda; 
            color: #155724; 
            border: 1px solid #c3e6cb; 
            border-radius: 5px; 
            padding: 10px; 
            margin: 10px auto; 
            max-width: 500px; 
        }
        .button {
        display: inline-block;
        
        background-color: #f1f1f1;
        color: #000;
        border-radius: 4px;
        text-decoration: none;
        border: none;
        }

        .button-blue {
        background-color: #3498db;
        padding: 4px 10px;
        color: #ffffff;
        }

        .button-red {
        background-color: #e74c3c;
        padding: 8px 16px;
        color: #fff;
        }
</style>

<script>
function confirmarEliminacion(event) {
  if (confirm("¿Estás seguro de que deseas eliminar este producto?")) {
    var url = "{% url 'productos:productos'  %}";

    // Redirect to a different URL after deleting the product
    window.location.href = "{% url 'productos:productos' %}";
  } else {
    event.preventDefault();
    return false;
  }
}

</script>

        <div class="search">
            <form action="{% url 'productos:productos' %}" method="get">
                <input type="text" name="buscar" placeholder="Buscar por nombre...">
                <button type="submit">Buscar</button>
               
            </form>
        </div>
        <hr>
        <form >
        <div>
            <!-- Ordenar por nombre? -->
            <!-- <select id="sortCriteria">
                <option value="nombre">Nombre</option>
                <option value="categoria">Categoría</option>
                <option value="subcategoria">SubCategoría</option>
                <option value="precio">Precio</option>
            </select> -->

        <button type="submit">Ver todos los productos</button>
        </form>
        </div>
         
        <div >
        {% for message in messages %}
            <p class="messages">{{ message }}</p>
        {% endfor %}
        </div>
        <div>
            <table border="1">
            <thead>
                <tr>
                    <th>Nombre </th>
                    <th>Imagen</th>
                    <th>Categoría </th>
                    <th>SubCategoría</th>
                    <th>Precio </th>
                    <th>Stock </th>
                    <th>Digital </th>
                    <th>Acciones</th>
                    <th>Descripción </th>
                </tr>
            </thead>
            <tbody id="tableBody">
                {% for productos in object_list %}
                <tr>
                    
                    
                    <td><p>{{ productos.nombre }}</p></td>
                    <!-- podría usar el thumbnail de image kit, pero ANITALIAS de PIL da error, ver después. -->
                    <td><img class="card-img-top thumbnail" src="{{ productos.image.url }}" alt="Imagen"></td>
                    <td>{{ productos.nombre_categoria }}</td>
                    <td>{{ productos.nombre_subcategoria }}</td>        
                    <td>{{ productos.precio }}</td>
                    <td>{{ productos.stock }}</td>
                    <td>
                    {% if productos.digital == True %}
                    <p>Sí</p>        
                    {% else %}
                    <p>No</p>
                    {% endif %}
                    </td>
                    <td><button class="button button-blue">
                        <a href="{% url 'productos:editar_producto' pk=productos.id %}" class="button button-blue">Editar</a></button>
                        <a href="{% url 'productos:eliminar_producto' pk=productos.id %}" class="button button-red" onclick="return confirmarEliminacion(event)">Eliminar</a>
                    </td>
                    <td>{{ productos.descripcion }}</td>


                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </body>

</html>
    
{% endblock contenido %}

apps/productos/templates/productos/sub_categorias.html
{% extends "core/base.html" %}

{% block contenido %}
<html>
    <body>
        
    <style>
        .button-style {
        display: inline-block;
        padding: 6px 14px;
        border-radius: 5px;
        text-decoration: none;
        font-weight: bold;
        color: #fff; /* Text color */
        background-color: #ff9900; /* Button background color */
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2); /* Add a subtle shadow */
        }

        .button-style:hover {
        background-color: #ffcc33; /* Button background color on hover */
        }

        .button-style:active {
        background-color: #ff6600; /* Button background color when clicked */
        }

    </style>

<script>
    function confirmarEliminacion(event) {
    if (confirm("¿Estás MUY seguro de que deseas eliminar esto?")) {
        
        // Redirect to a different URL after deleting the product
        window.location.href = "{% url 'index' %}";
    } else {
        event.preventDefault();
        return false;
    }
    }

</script>
        <h3 style="color: red">ATENCION. Al borrar una categoría, usted también eliminará todas las subcategorias asociadas a la misma. </h3>
        <div class="card">
    <ul>
        {% for categoria in categorias %}
        <li>
            <strong>Categoría:</strong>
            <a href="{% url 'productos:editar_categoria' pk=categoria.id %}" class="button-style">
            <span>{{ categoria.categoria_name }}</span>
            </a>
            <a href="{% url 'productos:eliminar_categoria' pk=categoria.id %}" class="btn btn-danger" onclick="return confirmarEliminacion(event)">Eliminar</a>
            
            <ul>
                {% for sub_categoria in sub_categorias %}
                {% if sub_categoria.categoria == categoria %}
                    <li>
                        <a href="{% url 'productos:eliminar_subcategoria' pk=sub_categoria.id %}" class="btn btn-danger" onclick="return confirmarEliminacion(event)">Eliminar</a>
                        <a href="{% url 'productos:editar_subcategoria' pk=sub_categoria.id %}" class="btn btn-info">{{ sub_categoria }}</a>

                    </li>
                {% endif %}
                
            {% endfor %}
            <hr>
            </ul>
        </li>
        {% endfor %}
    </ul>
</div>

<style>
    .card {
        border: 1px solid #000;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        padding: 10px;
    }

    ul {
        list-style-type: none;
        padding-left: 0;
    }

    li {
        margin-bottom: 5px;
        font-size: 20px;
    }
    
</style>


        
    </body>
</html>
    
{% endblock contenido %}