apps/cuentas/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "cuentas"

urlpatterns = [
    # Clientes
    # path("clientes/", views.ListClientes.as_view(), name="clientes"),
    # path("crud_clientes/", views.CrearCliente.as_view(), name="crear_cliente"),
    # path("editar_cliente/<pk>/", views.EditarCliente.as_view(), name="editar_cliente"),
    # # Users
    path("usuarios/", views.VerUsuarios.as_view(), name="usuarios"),
    path("registrar/", views.registrar_usuarios, name="registrar_usuarios"),
    path("login/", views.login_usuario, name="login"),
    path("logout/", views.logout_usuario, name="logout"),
    path("perfil/", views.perfil, name="perfil"),
    path("crear/editar_perfil/<pk>", views.EditarPerfil.as_view(), name="editar_perfil"),
]

apps/productos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from . import views

app_name = "productos"

urlpatterns = [
    # CATEGORIAS
    path("crear/categorias/", views.crear_categorias, name="crear_categorias"),
    path("crear/editar_categorias/<int:pk>/", views.UpdateCategorias.as_view(), name="editar_categoria"),
    path("productos/eliminar_categoria/<int:pk>/", views.eliminar_categoria, name="eliminar_categoria"),
    # SUB CATEGORIAS
    path("crear/sub_categorias/", views.crear_sub_categorias, name="crear_subcategorias"),
    path("productos/eliminar_subcategoria/<int:pk>/", views.eliminar_subcategoria, name="eliminar_subcategoria"),
    path("crear/editar_subcategorias/<int:pk>/", views.UpdateSubCategorias.as_view(), name="editar_subcategoria"),
    # AMBAS
    path("sub_categorias/", views.sub_categorias, name="mostrar_categorias_subcategorias"),
    # Esto asegura que se carguen correctamente los archivos de static
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("crear/", views.CrearProductos.as_view(), name="crear_productos"),
    path("productos/", views.ListProductos.as_view(), name="productos"),
    path("productos/eliminar_producto/<int:pk>/", views.eliminar_producto, name="eliminar_producto"),
    path("productos/editar_producto/<int:pk>/", views.UpdateProductos.as_view(), name="editar_producto"),
]

apps/ventas/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "ventas"

urlpatterns = [
    path("ventas/", views.ventas, name="ventas"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("cuentas/", include(("cuentas.urls", "cuentas"))),
    path("productos/", include(("productos.urls", "productos"))),
    path("ventas/", include(("ventas.urls", "ventas"))),
    path("", include(("core.urls", "core"))),
    path("Tienda/", include(("Tienda.urls", "Tienda"))),
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
    

    <title>Ecom</title>
</head>
<body>
<style>
        .message-box {
                background-color: green;
                color: white;
                padding: 10px;
                margin-bottom: 10px;
                margin-left: 450px;
                margin-right: 450px;
                border-radius: 5px;
            }
        .message-box.success {
                background-color: green;
            }

        .menu-button {
            background-color: #3498db; /* Azul */
            color: white;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            display: inline-block;
            width: 200px;
            text-decoration: none;
            text-align: center;
        }
        .productos {
    background-color: #9b59b6; /* Púrpura */
        }
        .agregar-producto {
            background-color: #2ecc71; /* Verde */
        }
        .agregar-categoria {
            background-color: #f1c40f; /* Amarillo */
        }
        .agregar-subcategoria {
            background-color: #e67e22; /* Naranja */
        }
        .categorias-subcategorias {
            background-color: #e74c3c; /* Rojo */
        }
        .ventas {
            background-color: #1abc9c; /* Turquesa */
        }
</style>
    {% include 'core/navbar.html' %}

    {% block contenido %}
        
    
        <div style="text-align: center">
        <h1 style= "color: red"> nashe (●'◡'●)</h1> 

    </div>
    <div style="text-align: center">
    
        <h1>Admin panel</h1>

            <div>
                <h2>Mi negocio</h2>
                <p>
                    <a href="{% url 'cuentas:usuarios' %}" class="menu-button usuarios">Usuarios</a>
                </p>
                <p>
                    <a href="{% url 'productos:productos' %}" class="menu-button productos">Productos</a>
                </p>
                <p>
                    <a href="productos/crear" class="menu-button agregar-producto">Agregar nuevo producto</a>
                </p>
                <p>
                    <a href="productos/crear/categorias" class="menu-button agregar-categoria">Agregar nueva categoría</a>
                </p>
                <p>
                    <a href="productos/crear/sub_categorias" class="menu-button agregar-subcategoria">Agregar nueva SUBcategoría</a>
                </p>
                <p>
                    <a href="productos/sub_categorias" class="menu-button categorias-subcategorias">Ver categorias y subcategorias</a>
                </p>
                <p>
                    <a href="{% url 'ventas:ventas' %}" class="menu-button ventas">Ventas</a>
                </p>
            
            {% for messages in messages %}
            <div class="message-box success">
                <h3>{{ messages }}</h3>
            </div>
            {% endfor %}
             </div>
    </div>
    <div style="text-align: center">
    <h2>Bienvenido/a {{ user }}!!</h2>
    <p>Bussines Manager es una web para gestionar su comercio. Posee una tienda virtual de productos para realizar ventas</p>
    <p>Hermano, como odio el frontend, ayuda. Usted podrá gestionar sus ventas en la tienda virtual</p>
    </div>
    {% endblock contenido %}

    {% include 'core/footer.html' %}
    </body>
</html>