apps/Tienda/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "Tienda"

urlpatterns = [
    path("tienda/", views.tienda, name="tienda"),
]

apps/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("about_me/", views.VerAboutMe.as_view(), name="about_me"),
    path("about_me_edit/", views.EditAboutMe.as_view(), name="editar_about_me"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cuentas/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "cuentas"

urlpatterns = [
    # Clientes
    # path("clientes/", views.ListClientes.as_view(), name="clientes"),
    # path("crud_clientes/", views.CrearCliente.as_view(), name="crear_cliente"),
    # path("editar_cliente/<pk>/", views.EditarCliente.as_view(), name="editar_cliente"),
    # # Users
    path("usuarios/", views.VerUsuarios.as_view(), name="usuarios"),
    path("registrar/", views.registrar_usuarios, name="registrar_usuarios"),
    path("login/", views.login_usuario, name="login"),
    path("logout/", views.logout_usuario, name="logout"),
    path("perfil/", views.perfil, name="perfil"),
    path("crear/editar_perfil/<pk>", views.EditarPerfil.as_view(), name="editar_perfil"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("cuentas/", include(("cuentas.urls", "cuentas"))),
    path("productos/", include(("productos.urls", "productos"))),
    path("ventas/", include(("ventas.urls", "ventas"))),
    path("", include(("core.urls", "core"))),
    path("Tienda/", include(("Tienda.urls", "Tienda"))),
]

apps/core/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from PIL import Image, ImageFilter


class AboutMeModel(models.Model):
    image = models.ImageField(upload_to="images", null=True, blank=True)
    thumbnail = ImageSpecField(
        source="image", processors=[ResizeToFit(100, 100)], format="JPEG", options={"quality": 90}
    )
    titulo = models.CharField(max_length=50, default="titulo", null=False, blank=False)
    texto_presentacion = models.TextField(max_length=500, null=False, blank=False)

    class Meta:
        verbose_name = "Presentación de la empresa"
        verbose_name_plural = "Presentaciones de la empresa"

    def __str__(self):
        return self.titulo

    @property
    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url

    # * Esto deberia permitir que se pueda editar el tamaño de la imagen por defecto sin front
    # * Como no funciona correctamente meto css y lo veo otro día en otro momento.
    # def resize_image(self):
    #     image = Image.open(self.image)
    #     image.thumbnail((300, 300))
    #     image.save(self.image.path)

    # def apply_antialias(self):
    #     # Example of applying antialiasing filter to the image using Pillow
    #     img = Image.open(self.image.path)
    #     antialiased_img = img.filter(ImageFilter.ANTIALIAS)
    #     antialiased_img.save(self.image.path)
    # * Ese es para el html
    # # <img src="{{ about_me.thumbnail.url }}" alt="Thumbnail">

apps/core/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from .models import AboutMeModel


class AboutMeForm(forms.ModelForm):
    class Meta:
        model = AboutMeModel
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        # Debría agregar estos botones automáticamente
        # Dado que estoy usando vista basada en clases no lo muestra.
        self.helper.add_input(Submit("submit", "Guardar"))

apps/core/views.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import AboutMeForm
from .models import AboutMeModel


class VerAboutMe(ListView):
    model = AboutMeModel
    template_name = "core/about_me.html"

    def about_me(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        prensentacion = AboutMeModel.objects.all()
        contexto["prensentacion"] = prensentacion
        return contexto


class EditAboutMe(CreateView):
    model = AboutMeModel
    template_name = "about_me_edit.html"
    form_class = AboutMeForm
    success_url = reverse_lazy("core:about_me")

apps/core/templates/core/about_me.html
{% extends "core/base.html" %}
{% load static %}
{% block contenido %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <style>
            .container {
                color: black;
                text-align: center;
            }
            body {
                background-color: #ffffff;
                margin: 0;
            }
            .box {
                margin-bottom: 20px;
                margin-left: 10px;
                margin-right: 10px;
            }

            .box h1 {
                font-size: 36px;
                font-weight: bold;
            }

            .box img {
                height: 600px;
                width: 550px;
            }

            .box p {
                font-size: 20px;
            }
            .info {
                margin-bottom: 20px;
                font-size: 20px;
            }
        
</style>

        <title>info</title>
    </head>
    <body>
        <div class="container">
            <h1>Ecommerce y BussinesManager</h1>

            <h2>Administrar tu negocio nunca fue tan elegante y fácil</h2>
            <div class="image">
                {% for about_me in object_list %}
                    <div class="box">
                        <h1>{{ about_me.titulo }}</h1>
                        <img src="{{ about_me.image.url }}" alt="La imagen no se puede cargar.">
                        <p>{{ about_me.texto_presentacion }}</p>
                    </div>
                {% empty %}
                <h2>Nuestro rubro y laburo</h2>
                <p>Larga trayectoria en el rubro de plantillas de ejemplo.</p>
                {% endfor %}
            </div>
            
        </div>
        <!-- Esto podrái cambiarlo en el about me -->
        
        <div class="info" style="text-align: center;">
            
                <h3>Contactanos</h3>
                
                <p>Email: MúsculusOfficial@gmail.com</p>
                
                <p>Celular / Whatsapp: + 54 9 261 599 6781 (Pablo) </p>
                <p>Celular / Whatsapp: + 54 9 261 322 3774 (Juan) </p>
             
        </div>
        <div class="info" style="text-align: center;">
            
                <h3>Horarios</h3>
                
                <p>De lunes a viernes: de 8:30hs - 21:30hs</p>
                
                <p>Sábados: de 8:30hs - 13:30hs   </p>
             
        </div>
    </body>
</html>
{% endblock contenido %}

apps/core/templates/core/about_me_edit.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block contenido %}
<!DOCTYPE html>
<html>
    <head>
        <style>
            .container {
                color: black;
                text-align: center;
            }
            body {
                background-color: #ffffff;
                margin: 0;
            }
        </style>
        <title>info</title>
    </head>
    <body>
        
        <h1>Editar About Me</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Guardar">
            {{form.errors}}
        </form>
        
    </body>
</html>
{% endblock contenido %}

apps/core/templates/core/base.html
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
<script src="{% static 'jquery.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Ecom</title>
</head>
<body>
    {% include 'core/navbar.html' %}
    
    {% block contenido %}
        
    {% endblock contenido %} 
    
    {% include 'core/footer.html' %}
</body>
</html>

apps/core/templates/core/footer.html
<html>

<style>
      footer a {
        display: inline-block;
        padding: 0.5rem 1rem;
        border-radius: 0.25rem;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
      }
</style>
<footer class="fixed-bottom bg-dark" style="height: 25px;">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Ioseph S.A. 2023</p></div>
</footer>
</html>

apps/core/templates/core/navbar.html
<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<!-- /Bootstrap -->

<!--Icons -->
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<!-- /Icons -->


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand mx-auto" href="{% url 'index'%}">BussinesManager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index'%}">
            <span class="material-icons">home</span>
            Lobby
            </a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Tienda:tienda'%}">
              <span class="material-icons">shopping_bag</span>
              Tienda
            </a>
          </li>
          
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:about_me'%}">
            <span class="material-icons">info</span>
            Info
          </a>
        </li>

        <li class="nav-item ml-auto">
          {% if request.user.is_authenticated %}
          <a class="nav-link " href="{% url 'cuentas:logout'%}">
            <span class="material-icons">logout</span>
            Salir
          </a>
            {% else %}
          <a class="nav-link " href="{% url 'cuentas:login'%}">
            <span class="material-icons">login</span>
            Ingresar
          </a>
          {% endif %}
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cuentas:perfil'%}">
            <span class="material-icons">account_circle</span>
            {{ request.user }}
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>