apps/cuentas/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "cuentas"

urlpatterns = [
    # Clientes
    # path("clientes/", views.ListClientes.as_view(), name="clientes"),
    # path("crud_clientes/", views.CrearCliente.as_view(), name="crear_cliente"),
    # path("editar_cliente/<pk>/", views.EditarCliente.as_view(), name="editar_cliente"),
    # # Users
    path("usuarios/", views.VerUsuarios.as_view(), name="usuarios"),
    path("registrar/", views.registrar_usuarios, name="registrar_usuarios"),
    path("login/", views.login_usuario, name="login"),
    path("logout/", views.logout_usuario, name="logout"),
    path("perfil/", views.perfil, name="perfil"),
    path("crear/editar_perfil/<pk>", views.EditarPerfil.as_view(), name="editar_perfil"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("cuentas/", include(("cuentas.urls", "cuentas"))),
    path("productos/", include(("productos.urls", "productos"))),
    path("ventas/", include(("ventas.urls", "ventas"))),
    path("", include(("core.urls", "core"))),
    path("Tienda/", include(("Tienda.urls", "Tienda"))),
]

apps/cuentas/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, User
from django.db import models

apps/cuentas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    profile_pic = forms.ImageField(required=False, widget=forms.FileInput)

    class Meta:
        model = User

        fields = ["username", "first_name", "last_name", "email", "password1", "password2", "profile_pic"]


class EditUserForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    profile_pic = forms.ImageField(required=False, widget=forms.FileInput)

    class Meta:
        model = User

        fields = ["first_name", "last_name", "email", "password1", "password2", "profile_pic"]

apps/cuentas/views.py
#  * Apps
from email import message

from cuentas.forms import CreateUserForm, UserCreationForm

# * django contrib
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

# * django views
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, UpdateView

from apps.cuentas.forms import EditUserForm

# * django imports


# Mostrar clientísimos
# class ListClientes(ListView):
#     model = Cliente
#     template_name = "clientes/clientes.html"
#     fields = "__all__"

#     def listar_clientes(self, **kwargs):
#         # Hereda  y extiende el contexto de la clase
#         contexto = super().get_context_data(**kwargs)

#         clientes = Cliente.objects.all()
#         contexto["clientes"] = clientes
#         return contexto

#     # Ordena en un query los clientes por orden alfabético del nombre
#     def get_queryset(self):
#         orden = super().get_queryset().order_by("nombre")
#         return orden


# class CrearCliente(CreateView):
#     model = Cliente
#     template_name = "clientes/crud_clientes.html"
#     success_url = reverse_lazy("clientes")
#     fields = "__all__"


# class EditarCliente(UpdateView):
#     model = Cliente
#     template_name = "clientes/crud_clientes.html"
#     success_url = reverse_lazy("clientes")
#     fields = "__all__"


# # class EliminarCliente(DeleteView):
# #     model = Cliente
# #     template_name = "clientes/crud_cliente.html"
# #     success_url = reverse_lazy("list_clientes")


class VerUsuarios(ListView):
    model = User
    template_name = "cuentas/usuarios.html"

    def listar_usuarios(self, **kwargs):
        # Hereda  y extiende el contexto de la clase
        contexto = super().get_context_data(**kwargs)

        usuarios = User.objects.all()
        contexto["usuarios"] = usuarios
        return contexto


def registrar_usuarios(request):
    # Evita que el usuario navege en registrar y login si ya ingresó
    if request.user.is_authenticated:
        return redirect("index")
    else:
        form = CreateUserForm()

        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                # Ver mensaje
                user = form.cleaned_data.get("username")
                messages.success(request, f"Usuario creado exitosamente:{user}")
                return redirect("cuentas:login")

        contexto = {"form": form}
        return render(request, "cuentas/registrar.html", contexto)


def login_usuario(request):
    # Evita que el usuario navege en registrar y login si ya ingresó
    if request.user.is_authenticated:
        return redirect("index")
    else:
        if request.method == "POST":
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("index")
            else:
                messages.error(request, "Usuario o contraseña incorrectos")
        contexto = {}
        return render(request, "cuentas/login.html", contexto)


@login_required(login_url="cuentas:login")
def logout_usuario(request):
    logout(request)
    return redirect("index")


@login_required(login_url="cuentas:login")
def perfil(request):
    contexto = {}
    user = User.objects.all()
    contexto["user"] = user
    return render(request, "perfil.html", contexto)


class EditarPerfil(UpdateView):
    template_name = "cuentas/crear.html"
    model = User
    form_class = EditUserForm

    success_url = reverse_lazy("cuentas:login")

apps/cuentas/templates/cuentas/clientes.html
{% extends "core/base.html" %}

{% block contenido %}
    <html>
        <body>
            
    <table border="1">
        <h1>Usted ha iniciado como: {{user}}</h1>     
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email </th>
                
            </tr>
        </thead>
        <tbody>
            {% for cliente in object_list  %}
            <tr>
                <td>{{ cliente.user }}</td>
                <td>{{ cliente.nombre }}</td>
                <td>{{ cliente.apellido }} </td>
                <td>{{ cliente.email }}</td>
               
            </tr>
            {% endfor %}
        </tbody>
    </table>
   
</div>
</body>
</html> 
{% endblock contenido %}

apps/cuentas/templates/cuentas/crear.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block contenido %}
<html>
    
    <body>
        <h1 id="editar_perfil-heading" style="text-align: center">Editar Perfil</h1>
        <a class="btn btn-warning" href= "{% url 'cuentas:perfil' %}" style="text-align: center"> &#8592; Volver al Perfil</a>
        <script>

    </script>
        <div class="container">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit"  value="Aceptar">
            </form>
        </div>
    </body>
</html>
{% endblock contenido %}

apps/cuentas/templates/cuentas/login.html
{% extends "core/base.html" %}
{% block contenido %}
<!DOCTYPE html>
<html lang="es">
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #20cee6;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #e4c411 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
                        
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                    
                {% for messages in messages %}
                <p style="background-color: #f8d7da; border: 1px solid #f5c6cb; padding: 10px; margin: 10px; color: red;">
                     {{ messages }}
                </p>

                {% endfor %}

                {{ form.errors }}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						No tiene una cuenta? <a href="{% url 'cuentas:registrar_usuarios' %}" class="ml-2">Registrarse</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>
{% endblock contenido %}

apps/cuentas/templates/cuentas/perfil.html
{% extends "core/base.html" %}

{% block contenido %}
<style>
	.profile-pic{
            max-width: 200px;
            max-height:200px;
            margin: 0 auto;
            border-radius: 50%;
        }
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href= "{% url 'index' %}"> &#8592; Volver a Inicio</a>
			<hr>
			<h3 style="text-align: center"> {{ request.user }} </h3>
			<hr>
            {% if request.user.profile_pic.url == None %}
                <p style="text-align: center">Debe agregar una foto</p>
            {% else %}
            <img class="profile-pic" src="{{ request.user.profile_pic.url }}" alt="Profile Picture" >
            {% endif %}
			
            
		</div>
	</div>
	<div class="col-md-9">
        <div class="card card-body">
			<h4 style="text-align: center"> Nombre: {{ request.user.first_name }} </h4>
			<hr>
			<h4 style="text-align: center"> Apellido: {{ request.user.last_name }} </h4>
			<hr>
			<h4 style="text-align: center"> Email: {{ request.user.email }} </h4>
			<hr>
			<a href="{% url 'cuentas:editar_perfil' pk=request.user.id %}" style="text-align: center">Editar Información Personal</a>
			<hr>
			<a href="{% url 'cuentas:editar_perfil' pk=request.user.id %}" style="text-align: center">Cambiar contraseña</a>

		</div>
	</div>
</div>
{% endblock contenido %}

apps/cuentas/templates/cuentas/registrar.html
{% extends "core/base.html" %}

{% block contenido %}
<html lang="es">
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	
    <title>Registrar</title>
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc   !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #20cee6;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #e4c411 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
    
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTRAR</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
                         
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.first_name }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.last_name }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square" ></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                	{{form.errors}}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Ya tiene una cuenta? <a href="{% url 'cuentas:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nombre de Usuario..';
		form_fields[2].placeholder='Nombre..';
		form_fields[3].placeholder='Apellido..';
		form_fields[4].placeholder='Email..';
		form_fields[5].placeholder='Ingrese Contraseña...';
		form_fields[6].placeholder='Confirmar Contraseña...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>


    </body>
</html>
{% endblock contenido %}

apps/cuentas/templates/cuentas/usuarios.html
{% extends 'core/base.html' %}

{% block contenido %}
<html>
        <body>
            <h1>Estos son los usuarios actuales</h1>
            <h2>Debería distingir entre staff y normales</h2>
            <table border="1">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email </th>
                        <th>Foto </th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in object_list %}
                    <tr>
                        <td>{{ user }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td><img src="{{ user.profile_pic.url }}" alt="Foto de Perfil"></td>
                        <td>
                            <a href="">Actualizar</a>
                            <a href="">Eliminar</a>
                            <a href=""></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        <!-- <ul>
            <li><a href="registrar">Agregar nuevo usuario</a></li>
        </ul> -->
        </body>
</html> 
{% endblock contenido %}